variables:
  DOCKER_REV: 3d0a10fa218be2f5e3cc0e68717c0b1a6d2909ad
  GIT_DEPTH: "1"

.x86_64-linux:
  tags:
    - x86_64-linux
  image: registry.gitlab.haskell.org/ghc/ci-images/x86_64-linux-ubuntu20_04:$DOCKER_REV
  before_script:
    - sudo chown ghc:ghc -R .
  script:
    - |
      PREFIX=/tmp/.ghc-wasm ./setup.sh
      . /tmp/.ghc-wasm/env

      pushd "$(mktemp -d)"
      echo "import System.Environment.Blank" >> hello.hs
      echo 'main = print =<< getArgs' >> hello.hs
      wasm32-wasi-ghc hello.hs -o hello.wasm
      $CROSS_EMULATOR ./hello.wasm "114 514" 233
      wasm-run ./hello.wasm "114 514" 233
      popd

x86_64-linux-int_gmp:
  extends: .x86_64-linux
  variables:
    BIGNUM_BACKEND: gmp

x86_64-linux-int_native:
  extends: .x86_64-linux
  variables:
    BIGNUM_BACKEND: native

x86_64-linux-nix:
  tags:
    - x86_64-linux
  image: nixos/nix:2.12.0
  before_script:
    - echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf
  script:
    - |
      nix build --json --no-link .
